name = "BidirectionalMaps"
uuid = "bd195279-2245-40d1-8987-184a0ce9e191"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "0.1.0"

[compat]
julia = "1.5"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

